"""Extracted from FTL: Multiverse 5.5.1 by apworld/tools/extract_mv.py, do not edit by hand."""

MV_VERSION = "5.5.1"

MV_SHIPS_RAW: tuple[tuple[int, str, str, tuple[str, ...]], ...] = (
    (10, 'PLAYER_SHIP_MVKESTREL', 'MV Kestrel Cruiser', ('A',)),
    (11, 'PLAYER_SHIP_MVFED', 'MV Federation Cruiser', ('A',)),
    (12, 'PLAYER_SHIP_MVSTEALTH', 'MV Stealth Cruiser', ('A',)),
    (13, 'PLAYER_SHIP_MVENGI', 'MV Harmony Cruiser', ('A',)),
    (14, 'PLAYER_SHIP_MVCIVILIAN', 'MV Union Cruiser', ('A',)),
    (15, 'PLAYER_SHIP_MVCRYSTAL', 'MV Imperial Cruiser', ('A',)),
    (16, 'PLAYER_SHIP_MVDYNASTY', 'MV Spectral Cruiser', ('A',)),
    (17, 'PLAYER_SHIP_MVLANIUS', 'MV Augmented Cruiser', ('A',)),
    (18, 'PLAYER_SHIP_PROTOMV', 'Proto-MV Cruiser', ('A', 'B', 'C')),
    (19, 'PLAYER_SHIP_UNION', 'Union Cruiser', ('A', 'B', 'C')),
    (20, 'PLAYER_SHIP_MILITIA', 'Militia Cruiser', ('A', 'B', 'C')),
    (21, 'PLAYER_SHIP_KESTREL', 'Kestrel Cruiser', ('A', 'B', 'C')),
    (22, 'PLAYER_SHIP_FEDERATION', 'Federation Cruiser', ('A', 'B', 'C')),
    (23, 'PLAYER_SHIP_CLOAK', 'Stealth Cruiser', ('A', 'B', 'C')),
    (24, 'PLAYER_SHIP_AUTO_FED', 'Federation Auto-Cruiser', ('A', 'B', 'C')),
    (25, 'PLAYER_SHIP_REBEL', 'Rebel Cruiser', ('A', 'B', 'C')),
    (26, 'PLAYER_SHIP_ENGINEER', 'Engineer Cruiser', ('A', 'B', 'C')),
    (27, 'PLAYER_SHIP_AUTO', 'Auto-Cruiser', ('A', 'B', 'C')),
    (28, 'PLAYER_SHIP_MVREBEL', 'MV Rebel Cruiser', ('A', 'B', 'C')),
    (29, 'PLAYER_SHIP_PROTOTYPE', 'Prototype Cruiser', ('A', 'B', 'C')),
    (30, 'PLAYER_SHIP_TUCO', "Tuco's Cruiser", ('A', 'B', 'C')),
    (31, 'PLAYER_SHIP_ENGI', 'Engi Cruiser', ('A', 'B', 'C')),
    (32, 'PLAYER_SHIP_SEPARATIST', 'Separatist Cruiser', ('A', 'B', 'C')),
    (33, 'PLAYER_SHIP_ZOLTAN', 'Ministry Cruiser', ('A', 'B', 'C')),
    (34, 'PLAYER_SHIP_DUSKBRINGER', 'Duskbringer Cruiser', ('A', 'B', 'C')),
    (35, 'PLAYER_SHIP_MONK', 'Illesctrian Cruiser', ('A', 'B', 'C')),
    (36, 'PLAYER_SHIP_HIVE', 'Hive Cruiser', ('A', 'B', 'C')),
    (37, 'PLAYER_SHIP_FREEMANTIS', 'Free Mantis Cruiser', ('A', 'B', 'C')),
    (38, 'PLAYER_SHIP_SUZERAIN', 'Suzerain Cruiser', ('A', 'B', 'C')),
    (39, 'PLAYER_SHIP_ROCKMAN', 'Theocracy Cruiser', ('A', 'B', 'C')),
    (40, 'PLAYER_SHIP_OUTCAST', 'Outcast Cruiser', ('A', 'B', 'C')),
    (41, 'PLAYER_SHIP_LOSTSUN', 'Lost Sun Cruiser', ('A', 'B', 'C')),
    (42, 'PLAYER_SHIP_SSLG', 'SSLG Cruiser', ('A', 'B', 'C')),
    (43, 'PLAYER_SHIP_CRYSTALLINE', 'Imperial Cruiser', ('A', 'B', 'C')),
    (44, 'PLAYER_SHIP_SLUG', 'Kleptocracy Cruiser', ('A', 'B', 'C')),
    (45, 'PLAYER_SHIP_CLAN', 'Guild Cruiser', ('A', 'B', 'C')),
    (46, 'PLAYER_SHIP_HEKTAR', 'Hektar Cruiser(tm)', ('A', 'B', 'C')),
    (47, 'PLAYER_SHIP_HACKER', 'Hacker Cruiser', ('A', 'B', 'C')),
    (48, 'PLAYER_SHIP_SYLVAN', "Sylvan's Cruiser", ('A', 'B', 'C')),
    (49, 'PLAYER_SHIP_ORCHID', 'Gathering Cruiser', ('A', 'B', 'C')),
    (50, 'PLAYER_SHIP_VAMPWEED', 'Confederate Cruiser', ('A', 'B', 'C')),
    (51, 'PLAYER_SHIP_CARETAKER', 'Caretaker Cruiser', ('A', 'B', 'C')),
    (52, 'PLAYER_SHIP_CULTIVATOR', 'Cultivator Cruiser', ('A', 'B', 'C')),
    (53, 'PLAYER_SHIP_SHELL', 'Geniocracy Cruiser', ('A', 'B', 'C')),
    (54, 'PLAYER_SHIP_SCIENTIST', 'Geniocracy Science Cruiser', ('A', 'B', 'C')),
    (55, 'PLAYER_SHIP_MECHANIC', 'Geniocracy Management Cruiser', ('A', 'B', 'C')),
    (56, 'PLAYER_SHIP_LEECH', 'Republican Cruiser', ('A', 'B', 'C')),
    (57, 'PLAYER_SHIP_ALKRAM', 'Revolutionary Cruiser', ('A', 'B', 'C')),
    (58, 'PLAYER_SHIP_TONY', 'Retail Cruiser', ('A', 'B', 'C')),
    (59, 'PLAYER_SHIP_COALITION', 'Coalition Cruiser', ('A', 'B', 'C')),
    (60, 'PLAYER_SHIP_LANIUS', 'Lanius Cruiser', ('A', 'B', 'C')),
    (61, 'PLAYER_SHIP_DYNASTY', 'Spectral Cruiser', ('A', 'B', 'C')),
    (62, 'PLAYER_SHIP_GHOST', 'Spook Chaser Cruiser', ('A', 'B', 'C')),
    (63, 'PLAYER_SHIP_PLEASUREFLAG', 'The Pleasure Flagship', ('A',)),
    (64, 'PLAYER_SHIP_STUPIDGHOST', 'Wrecked Bomber', ('A', 'B', 'C')),
)

MV_LAYOUT_SYSTEMS_RAW: tuple[tuple[str, tuple[str, ...]], ...] = (
    ('PLAYER_SHIP_MVKESTREL', ('doors', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_MVFED', ('artillery', 'doors', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_MVSTEALTH', ('cloaking', 'clonebay', 'doors', 'engines', 'oxygen', 'pilot', 'sensors', 'weapons')),
    ('PLAYER_SHIP_MVENGI', ('doors', 'drones', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_MVCIVILIAN', ('doors', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_MVCRYSTAL', ('clonebay', 'doors', 'engines', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_MVDYNASTY', ('clonebay', 'doors', 'engines', 'oxygen', 'pilot', 'sensors', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_MVLANIUS', ('cloaking', 'doors', 'engines', 'medbay', 'pilot', 'sensors', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_PROTOMV', ('doors', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_PROTOMV_2', ('doors', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_PROTOMV_3', ('cloaking', 'clonebay', 'doors', 'engines', 'oxygen', 'pilot', 'sensors', 'weapons')),
    ('PLAYER_SHIP_UNION', ('doors', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_UNION_2', ('doors', 'engines', 'oxygen', 'pilot', 'sensors', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_UNION_3', ('clonebay', 'doors', 'engines', 'mind', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_MILITIA', ('doors', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_MILITIA_2', ('doors', 'drones', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_MILITIA_3', ('cloaking', 'clonebay', 'doors', 'engines', 'oxygen', 'pilot', 'sensors', 'weapons')),
    ('PLAYER_SHIP_KESTREL', ('doors', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_KESTREL_2', ('doors', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_KESTREL_3', ('cloaking', 'clonebay', 'doors', 'engines', 'oxygen', 'pilot', 'sensors', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_FEDERATION', ('artillery', 'doors', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_FEDERATION_2', ('artillery', 'doors', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_FEDERATION_3', ('artillery', 'clonebay', 'doors', 'engines', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_CLOAK', ('battery', 'cloaking', 'doors', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'weapons')),
    ('PLAYER_SHIP_CLOAK_2', ('cloaking', 'doors', 'engines', 'hacking', 'medbay', 'oxygen', 'pilot', 'sensors', 'weapons')),
    ('PLAYER_SHIP_CLOAK_3', ('cloaking', 'clonebay', 'doors', 'engines', 'mind', 'oxygen', 'pilot', 'sensors', 'weapons')),
    ('PLAYER_SHIP_AUTO_FED', ('doors', 'drones', 'engines', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_AUTO_FED_2', ('cloaking', 'engines', 'medbay', 'pilot', 'sensors', 'weapons')),
    ('PLAYER_SHIP_AUTO_FED_3', ('doors', 'drones', 'engines', 'oxygen', 'pilot', 'sensors', 'shields', 'teleporter')),
    ('PLAYER_SHIP_REBEL', ('artillery', 'doors', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_REBEL_2', ('artillery', 'doors', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_REBEL_3', ('artillery', 'battery', 'clonebay', 'doors', 'engines', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_ENGINEER', ('doors', 'drones', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_ENGINEER_2', ('doors', 'drones', 'engines', 'oxygen', 'pilot', 'sensors', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_ENGINEER_3', ('clonebay', 'doors', 'drones', 'engines', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_AUTO', ('doors', 'drones', 'engines', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_AUTO_2', ('battery', 'doors', 'drones', 'engines', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_AUTO_3', ('engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_MVREBEL', ('doors', 'drones', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_MVREBEL_2', ('battery', 'doors', 'drones', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_MVREBEL_3', ('clonebay', 'doors', 'drones', 'engines', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_PROTOTYPE', ('battery', 'doors', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_PROTOTYPE_2', ('battery', 'doors', 'drones', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_PROTOTYPE_3', ('clonebay', 'doors', 'drones', 'engines', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_TUCO', ('doors', 'engines', 'hacking', 'medbay', 'oxygen', 'pilot', 'shields', 'weapons')),
    ('PLAYER_SHIP_TUCO_2', ('battery', 'doors', 'engines', 'medbay', 'mind', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_TUCO_3', ('clonebay', 'doors', 'engines', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_ENGI', ('doors', 'drones', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_ENGI_2', ('doors', 'drones', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'weapons')),
    ('PLAYER_SHIP_ENGI_3', ('doors', 'drones', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_SEPARATIST', ('clonebay', 'doors', 'drones', 'engines', 'pilot', 'shields', 'weapons')),
    ('PLAYER_SHIP_SEPARATIST_2', ('clonebay', 'doors', 'drones', 'engines', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_SEPARATIST_3', ('clonebay', 'doors', 'drones', 'engines', 'pilot', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_ZOLTAN', ('doors', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_ZOLTAN_2', ('doors', 'drones', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'weapons')),
    ('PLAYER_SHIP_ZOLTAN_3', ('clonebay', 'doors', 'engines', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_DUSKBRINGER', ('clonebay', 'doors', 'engines', 'oxygen', 'pilot', 'sensors', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_DUSKBRINGER_2', ('cloaking', 'clonebay', 'doors', 'engines', 'oxygen', 'pilot', 'sensors', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_DUSKBRINGER_3', ('battery', 'clonebay', 'doors', 'drones', 'engines', 'oxygen', 'pilot', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_MONK', ('battery', 'doors', 'drones', 'engines', 'medbay', 'mind', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_MONK_2', ('doors', 'drones', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_MONK_3', ('clonebay', 'doors', 'engines', 'oxygen', 'pilot', 'sensors', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_HIVE', ('doors', 'engines', 'medbay', 'oxygen', 'pilot', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_HIVE_2', ('doors', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_HIVE_3', ('clonebay', 'doors', 'engines', 'oxygen', 'pilot', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_FREEMANTIS', ('engines', 'medbay', 'mind', 'oxygen', 'pilot', 'sensors', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_FREEMANTIS_2', ('cloaking', 'doors', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_FREEMANTIS_3', ('battery', 'clonebay', 'doors', 'engines', 'oxygen', 'pilot', 'sensors', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_SUZERAIN', ('doors', 'drones', 'engines', 'medbay', 'oxygen', 'pilot', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_SUZERAIN_2', ('cloaking', 'doors', 'engines', 'hacking', 'medbay', 'oxygen', 'pilot', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_SUZERAIN_3', ('clonebay', 'drones', 'engines', 'oxygen', 'pilot', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_ROCKMAN', ('doors', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_ROCKMAN_2', ('doors', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_ROCKMAN_3', ('cloaking', 'clonebay', 'doors', 'engines', 'oxygen', 'pilot', 'sensors', 'weapons')),
    ('PLAYER_SHIP_OUTCAST', ('doors', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_OUTCAST_2', ('doors', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'teleporter')),
    ('PLAYER_SHIP_OUTCAST_3', ('battery', 'doors', 'engines', 'oxygen', 'pilot', 'sensors', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_LOSTSUN', ('engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_LOSTSUN_2', ('engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_LOSTSUN_3', ('clonebay', 'drones', 'engines', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_SSLG', ('engines', 'medbay', 'mind', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_SSLG_2', ('doors', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_SSLG_3', ('clonebay', 'doors', 'drones', 'engines', 'oxygen', 'pilot', 'sensors', 'weapons')),
    ('PLAYER_SHIP_CRYSTALLINE', ('doors', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_CRYSTALLINE_2', ('engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_CRYSTALLINE_3', ('clonebay', 'doors', 'engines', 'oxygen', 'pilot', 'sensors', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_SLUG', ('doors', 'engines', 'medbay', 'oxygen', 'pilot', 'shields', 'weapons')),
    ('PLAYER_SHIP_SLUG_2', ('battery', 'doors', 'engines', 'hacking', 'medbay', 'oxygen', 'pilot', 'shields', 'weapons')),
    ('PLAYER_SHIP_SLUG_3', ('clonebay', 'doors', 'drones', 'engines', 'oxygen', 'pilot', 'shields', 'weapons')),
    ('PLAYER_SHIP_CLAN', ('doors', 'engines', 'medbay', 'oxygen', 'pilot', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_CLAN_2', ('doors', 'engines', 'medbay', 'oxygen', 'pilot', 'shields', 'weapons')),
    ('PLAYER_SHIP_CLAN_3', ('doors', 'engines', 'oxygen', 'pilot', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_HEKTAR', ('doors', 'engines', 'medbay', 'oxygen', 'pilot', 'shields', 'weapons')),
    ('PLAYER_SHIP_HEKTAR_2', ('doors', 'engines', 'hacking', 'medbay', 'oxygen', 'pilot', 'shields', 'weapons')),
    ('PLAYER_SHIP_HEKTAR_3', ('clonebay', 'doors', 'engines', 'oxygen', 'pilot', 'shields', 'weapons')),
    ('PLAYER_SHIP_HACKER', ('battery', 'doors', 'drones', 'engines', 'hacking', 'medbay', 'oxygen', 'pilot', 'shields', 'weapons')),
    ('PLAYER_SHIP_HACKER_2', ('doors', 'engines', 'hacking', 'medbay', 'oxygen', 'pilot', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_HACKER_3', ('clonebay', 'doors', 'drones', 'engines', 'hacking', 'oxygen', 'pilot', 'shields', 'weapons')),
    ('PLAYER_SHIP_SYLVAN', ('doors', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'weapons')),
    ('PLAYER_SHIP_SYLVAN_2', ('clonebay', 'doors', 'drones', 'engines', 'oxygen', 'pilot', 'sensors', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_SYLVAN_3', ('battery', 'cloaking', 'clonebay', 'doors', 'engines', 'oxygen', 'pilot', 'sensors', 'weapons')),
    ('PLAYER_SHIP_ORCHID', ('doors', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_ORCHID_2', ('cloaking', 'doors', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'weapons')),
    ('PLAYER_SHIP_ORCHID_3', ('clonebay', 'engines', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_VAMPWEED', ('drones', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_VAMPWEED_2', ('doors', 'drones', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_VAMPWEED_3', ('clonebay', 'doors', 'engines', 'mind', 'oxygen', 'pilot', 'sensors', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_CARETAKER', ('doors', 'engines', 'medbay', 'pilot', 'shields', 'weapons')),
    ('PLAYER_SHIP_CARETAKER_2', ('doors', 'engines', 'medbay', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_CARETAKER_3', ('clonebay', 'doors', 'engines', 'pilot', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_CULTIVATOR', ('doors', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_CULTIVATOR_2', ('clonebay', 'doors', 'drones', 'engines', 'oxygen', 'pilot', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_CULTIVATOR_3', ('battery', 'clonebay', 'doors', 'drones', 'engines', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_SHELL', ('doors', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_SHELL_2', ('doors', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_SHELL_3', ('clonebay', 'doors', 'engines', 'mind', 'oxygen', 'pilot', 'sensors', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_SCIENTIST', ('doors', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_SCIENTIST_2', ('doors', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_SCIENTIST_3', ('doors', 'engines', 'mind', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_MECHANIC', ('doors', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_MECHANIC_2', ('doors', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_MECHANIC_3', ('cloaking', 'clonebay', 'doors', 'engines', 'oxygen', 'pilot', 'sensors', 'weapons')),
    ('PLAYER_SHIP_LEECH', ('battery', 'doors', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_LEECH_2', ('battery', 'doors', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_LEECH_3', ('cloaking', 'clonebay', 'doors', 'engines', 'hacking', 'oxygen', 'pilot', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_ALKRAM', ('doors', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_ALKRAM_2', ('doors', 'engines', 'oxygen', 'pilot', 'sensors', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_ALKRAM_3', ('clonebay', 'doors', 'engines', 'hacking', 'oxygen', 'pilot', 'sensors', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_TONY', ('battery', 'doors', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_TONY_2', ('doors', 'drones', 'engines', 'oxygen', 'pilot', 'sensors', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_TONY_3', ('battery', 'clonebay', 'doors', 'engines', 'oxygen', 'pilot', 'sensors', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_COALITION', ('cloaking', 'doors', 'engines', 'medbay', 'oxygen', 'pilot', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_COALITION_2', ('clonebay', 'doors', 'engines', 'oxygen', 'pilot', 'sensors', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_COALITION_3', ('clonebay', 'engines', 'mind', 'oxygen', 'pilot', 'shields', 'weapons')),
    ('PLAYER_SHIP_LANIUS', ('doors', 'engines', 'hacking', 'medbay', 'pilot', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_LANIUS_2', ('doors', 'drones', 'engines', 'medbay', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_LANIUS_3', ('cloaking', 'clonebay', 'doors', 'engines', 'oxygen', 'pilot', 'sensors', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_DYNASTY', ('cloaking', 'doors', 'engines', 'medbay', 'pilot', 'sensors', 'weapons')),
    ('PLAYER_SHIP_DYNASTY_2', ('doors', 'engines', 'medbay', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_DYNASTY_3', ('clonebay', 'doors', 'engines', 'pilot', 'sensors', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_GHOST', ('doors', 'drones', 'engines', 'medbay', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_GHOST_2', ('doors', 'engines', 'medbay', 'oxygen', 'pilot', 'shields', 'weapons')),
    ('PLAYER_SHIP_GHOST_3', ('battery', 'clonebay', 'engines', 'oxygen', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_PLEASUREFLAG', ('cloaking', 'doors', 'drones', 'engines', 'oxygen', 'pilot', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_STUPIDGHOST', ('cloaking', 'doors', 'engines', 'medbay', 'pilot', 'sensors', 'shields', 'teleporter', 'weapons')),
    ('PLAYER_SHIP_STUPIDGHOST_2', ('clonebay', 'doors', 'drones', 'engines', 'hacking', 'pilot', 'sensors', 'shields', 'weapons')),
    ('PLAYER_SHIP_STUPIDGHOST_3', ('clonebay', 'drones', 'engines', 'oxygen', 'pilot', 'sensors', 'shields', 'teleporter', 'weapons')),
)

MV_LAYOUT_EMPTY_SLOTS_RAW: tuple[tuple[str, tuple[str, ...]], ...] = (
    ('PLAYER_SHIP_MVKESTREL', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'mind', 'teleporter')),
    ('PLAYER_SHIP_MVFED', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'mind', 'teleporter')),
    ('PLAYER_SHIP_MVSTEALTH', ('battery', 'drones', 'hacking', 'medbay', 'mind', 'shields', 'teleporter')),
    ('PLAYER_SHIP_MVENGI', ('battery', 'cloaking', 'clonebay', 'hacking', 'mind', 'teleporter')),
    ('PLAYER_SHIP_MVCIVILIAN', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'mind')),
    ('PLAYER_SHIP_MVCRYSTAL', ('battery', 'cloaking', 'drones', 'hacking', 'medbay', 'mind', 'teleporter')),
    ('PLAYER_SHIP_MVDYNASTY', ('battery', 'cloaking', 'drones', 'hacking', 'medbay', 'mind')),
    ('PLAYER_SHIP_MVLANIUS', ('battery', 'clonebay', 'drones', 'hacking', 'mind', 'oxygen')),
    ('PLAYER_SHIP_PROTOMV', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'mind', 'teleporter')),
    ('PLAYER_SHIP_PROTOMV_2', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'mind', 'teleporter')),
    ('PLAYER_SHIP_PROTOMV_3', ('battery', 'drones', 'hacking', 'medbay', 'mind', 'shields', 'teleporter')),
    ('PLAYER_SHIP_UNION', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'mind', 'teleporter')),
    ('PLAYER_SHIP_UNION_2', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'medbay', 'mind')),
    ('PLAYER_SHIP_UNION_3', ('battery', 'cloaking', 'drones', 'hacking', 'medbay', 'teleporter')),
    ('PLAYER_SHIP_MILITIA', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'mind', 'teleporter')),
    ('PLAYER_SHIP_MILITIA_2', ('battery', 'cloaking', 'clonebay', 'hacking', 'mind', 'teleporter')),
    ('PLAYER_SHIP_MILITIA_3', ('battery', 'drones', 'hacking', 'medbay', 'mind', 'shields', 'teleporter')),
    ('PLAYER_SHIP_KESTREL', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'mind', 'teleporter')),
    ('PLAYER_SHIP_KESTREL_2', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'mind', 'teleporter')),
    ('PLAYER_SHIP_KESTREL_3', ('battery', 'drones', 'hacking', 'medbay', 'mind')),
    ('PLAYER_SHIP_FEDERATION', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'mind', 'teleporter')),
    ('PLAYER_SHIP_FEDERATION_2', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'mind', 'teleporter')),
    ('PLAYER_SHIP_FEDERATION_3', ('battery', 'cloaking', 'drones', 'hacking', 'medbay', 'mind', 'teleporter')),
    ('PLAYER_SHIP_CLOAK', ('clonebay', 'drones', 'hacking', 'mind', 'shields', 'teleporter')),
    ('PLAYER_SHIP_CLOAK_2', ('battery', 'clonebay', 'drones', 'mind', 'shields', 'teleporter')),
    ('PLAYER_SHIP_CLOAK_3', ('battery', 'drones', 'hacking', 'medbay', 'shields', 'teleporter')),
    ('PLAYER_SHIP_AUTO_FED', ('battery', 'cloaking', 'clonebay', 'hacking', 'medbay', 'mind', 'oxygen', 'teleporter')),
    ('PLAYER_SHIP_AUTO_FED_2', ('battery', 'clonebay', 'doors', 'drones', 'hacking', 'mind', 'oxygen', 'shields', 'teleporter')),
    ('PLAYER_SHIP_AUTO_FED_3', ('battery', 'cloaking', 'clonebay', 'hacking', 'medbay', 'mind', 'weapons')),
    ('PLAYER_SHIP_REBEL', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'mind', 'teleporter')),
    ('PLAYER_SHIP_REBEL_2', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'mind', 'teleporter')),
    ('PLAYER_SHIP_REBEL_3', ('cloaking', 'drones', 'hacking', 'medbay', 'mind', 'teleporter')),
    ('PLAYER_SHIP_ENGINEER', ('battery', 'cloaking', 'clonebay', 'hacking', 'mind', 'teleporter')),
    ('PLAYER_SHIP_ENGINEER_2', ('battery', 'cloaking', 'clonebay', 'hacking', 'medbay', 'mind')),
    ('PLAYER_SHIP_ENGINEER_3', ('battery', 'cloaking', 'hacking', 'medbay', 'mind', 'teleporter')),
    ('PLAYER_SHIP_AUTO', ('battery', 'cloaking', 'clonebay', 'hacking', 'medbay', 'mind', 'oxygen', 'teleporter')),
    ('PLAYER_SHIP_AUTO_2', ('cloaking', 'hacking', 'mind')),
    ('PLAYER_SHIP_AUTO_3', ('battery', 'cloaking', 'clonebay', 'doors', 'drones', 'hacking', 'mind', 'teleporter')),
    ('PLAYER_SHIP_MVREBEL', ('battery', 'cloaking', 'clonebay', 'hacking', 'mind', 'teleporter')),
    ('PLAYER_SHIP_MVREBEL_2', ('cloaking', 'clonebay', 'hacking', 'mind', 'teleporter')),
    ('PLAYER_SHIP_MVREBEL_3', ('battery', 'cloaking', 'hacking', 'medbay', 'mind', 'teleporter')),
    ('PLAYER_SHIP_PROTOTYPE', ('cloaking', 'clonebay', 'drones', 'hacking', 'mind')),
    ('PLAYER_SHIP_PROTOTYPE_2', ('cloaking', 'clonebay', 'hacking', 'mind', 'teleporter')),
    ('PLAYER_SHIP_PROTOTYPE_3', ('battery', 'cloaking', 'hacking', 'medbay', 'mind', 'teleporter')),
    ('PLAYER_SHIP_TUCO', ('battery', 'cloaking', 'clonebay', 'drones', 'mind', 'sensors', 'teleporter')),
    ('PLAYER_SHIP_TUCO_2', ('cloaking', 'clonebay', 'drones', 'hacking', 'teleporter')),
    ('PLAYER_SHIP_TUCO_3', ('battery', 'cloaking', 'drones', 'hacking', 'medbay', 'mind', 'teleporter')),
    ('PLAYER_SHIP_ENGI', ('battery', 'cloaking', 'clonebay', 'hacking', 'mind', 'teleporter')),
    ('PLAYER_SHIP_ENGI_2', ('battery', 'cloaking', 'clonebay', 'hacking', 'mind', 'shields', 'teleporter')),
    ('PLAYER_SHIP_ENGI_3', ('battery', 'cloaking', 'clonebay', 'hacking', 'mind')),
    ('PLAYER_SHIP_SEPARATIST', ('battery', 'cloaking', 'hacking', 'medbay', 'mind', 'oxygen', 'sensors', 'teleporter')),
    ('PLAYER_SHIP_SEPARATIST_2', ('battery', 'cloaking', 'hacking', 'medbay', 'mind', 'teleporter')),
    ('PLAYER_SHIP_SEPARATIST_3', ('battery', 'cloaking', 'hacking', 'medbay', 'mind', 'oxygen', 'sensors')),
    ('PLAYER_SHIP_ZOLTAN', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'mind', 'teleporter')),
    ('PLAYER_SHIP_ZOLTAN_2', ('battery', 'cloaking', 'clonebay', 'hacking', 'mind', 'shields', 'teleporter')),
    ('PLAYER_SHIP_ZOLTAN_3', ('battery', 'cloaking', 'drones', 'hacking', 'medbay', 'mind', 'teleporter')),
    ('PLAYER_SHIP_DUSKBRINGER', ('battery', 'cloaking', 'drones', 'hacking', 'medbay', 'mind')),
    ('PLAYER_SHIP_DUSKBRINGER_2', ('battery', 'drones', 'hacking', 'medbay', 'mind', 'shields')),
    ('PLAYER_SHIP_DUSKBRINGER_3', ('cloaking', 'hacking', 'medbay', 'mind', 'sensors')),
    ('PLAYER_SHIP_MONK', ('cloaking', 'clonebay', 'hacking', 'teleporter')),
    ('PLAYER_SHIP_MONK_2', ('battery', 'cloaking', 'clonebay', 'hacking', 'mind', 'teleporter')),
    ('PLAYER_SHIP_MONK_3', ('battery', 'cloaking', 'drones', 'hacking', 'medbay', 'mind')),
    ('PLAYER_SHIP_HIVE', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'mind', 'sensors')),
    ('PLAYER_SHIP_HIVE_2', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'mind', 'teleporter')),
    ('PLAYER_SHIP_HIVE_3', ('battery', 'cloaking', 'drones', 'hacking', 'medbay', 'mind', 'sensors')),
    ('PLAYER_SHIP_FREEMANTIS', ('battery', 'cloaking', 'clonebay', 'doors', 'drones', 'hacking')),
    ('PLAYER_SHIP_FREEMANTIS_2', ('battery', 'clonebay', 'drones', 'hacking', 'mind', 'shields')),
    ('PLAYER_SHIP_FREEMANTIS_3', ('cloaking', 'drones', 'hacking', 'medbay', 'mind')),
    ('PLAYER_SHIP_SUZERAIN', ('battery', 'cloaking', 'clonebay', 'hacking', 'mind', 'sensors')),
    ('PLAYER_SHIP_SUZERAIN_2', ('battery', 'clonebay', 'drones', 'mind', 'sensors', 'shields')),
    ('PLAYER_SHIP_SUZERAIN_3', ('battery', 'cloaking', 'doors', 'hacking', 'medbay', 'mind', 'sensors')),
    ('PLAYER_SHIP_ROCKMAN', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'mind', 'teleporter')),
    ('PLAYER_SHIP_ROCKMAN_2', ('battery', 'cloaking', 'drones', 'hacking', 'clonebay', 'mind', 'teleporter')),
    ('PLAYER_SHIP_ROCKMAN_3', ('battery', 'drones', 'hacking', 'medbay', 'mind', 'shields', 'teleporter')),
    ('PLAYER_SHIP_OUTCAST', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'mind')),
    ('PLAYER_SHIP_OUTCAST_2', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'mind', 'weapons')),
    ('PLAYER_SHIP_OUTCAST_3', ('cloaking', 'clonebay', 'drones', 'hacking', 'medbay', 'mind')),
    ('PLAYER_SHIP_LOSTSUN', ('battery', 'cloaking', 'clonebay', 'doors', 'drones', 'hacking', 'mind')),
    ('PLAYER_SHIP_LOSTSUN_2', ('battery', 'cloaking', 'clonebay', 'doors', 'drones', 'hacking', 'mind')),
    ('PLAYER_SHIP_LOSTSUN_3', ('battery', 'cloaking', 'doors', 'hacking', 'medbay', 'mind', 'teleporter')),
    ('PLAYER_SHIP_SSLG', ('battery', 'cloaking', 'clonebay', 'doors', 'drones', 'hacking', 'teleporter')),
    ('PLAYER_SHIP_SSLG_2', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'mind')),
    ('PLAYER_SHIP_SSLG_3', ('battery', 'cloaking', 'hacking', 'medbay', 'mind', 'shields', 'teleporter')),
    ('PLAYER_SHIP_CRYSTALLINE', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'mind', 'teleporter')),
    ('PLAYER_SHIP_CRYSTALLINE_2', ('battery', 'cloaking', 'clonebay', 'doors', 'drones', 'hacking', 'mind')),
    ('PLAYER_SHIP_CRYSTALLINE_3', ('battery', 'cloaking', 'drones', 'hacking', 'medbay', 'mind')),
    ('PLAYER_SHIP_SLUG', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'mind', 'sensors', 'teleporter')),
    ('PLAYER_SHIP_SLUG_2', ('cloaking', 'clonebay', 'drones', 'mind', 'sensors', 'teleporter')),
    ('PLAYER_SHIP_SLUG_3', ('battery', 'cloaking', 'hacking', 'medbay', 'mind', 'sensors', 'teleporter')),
    ('PLAYER_SHIP_CLAN', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'mind', 'sensors')),
    ('PLAYER_SHIP_CLAN_2', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'mind', 'sensors', 'teleporter')),
    ('PLAYER_SHIP_CLAN_3', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'medbay', 'mind', 'sensors')),
    ('PLAYER_SHIP_HEKTAR', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'mind', 'sensors', 'teleporter')),
    ('PLAYER_SHIP_HEKTAR_2', ('battery', 'cloaking', 'clonebay', 'drones', 'mind', 'sensors', 'teleporter')),
    ('PLAYER_SHIP_HEKTAR_3', ('battery', 'cloaking', 'drones', 'hacking', 'medbay', 'mind', 'sensors', 'teleporter')),
    ('PLAYER_SHIP_HACKER', ('cloaking', 'clonebay', 'mind', 'sensors', 'teleporter')),
    ('PLAYER_SHIP_HACKER_2', ('battery', 'cloaking', 'clonebay', 'drones', 'mind', 'sensors')),
    ('PLAYER_SHIP_HACKER_3', ('battery', 'cloaking', 'medbay', 'mind', 'sensors', 'teleporter')),
    ('PLAYER_SHIP_SYLVAN', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'mind', 'shields', 'teleporter')),
    ('PLAYER_SHIP_SYLVAN_2', ('battery', 'cloaking', 'hacking', 'medbay', 'mind')),
    ('PLAYER_SHIP_SYLVAN_3', ('drones', 'hacking', 'medbay', 'mind', 'shields', 'teleporter')),
    ('PLAYER_SHIP_ORCHID', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'mind', 'teleporter')),
    ('PLAYER_SHIP_ORCHID_2', ('battery', 'clonebay', 'drones', 'hacking', 'mind', 'shields', 'teleporter')),
    ('PLAYER_SHIP_ORCHID_3', ('battery', 'cloaking', 'doors', 'drones', 'hacking', 'medbay', 'mind', 'teleporter')),
    ('PLAYER_SHIP_VAMPWEED', ('battery', 'cloaking', 'clonebay', 'doors', 'hacking', 'mind')),
    ('PLAYER_SHIP_VAMPWEED_2', ('battery', 'cloaking', 'clonebay', 'hacking', 'mind', 'teleporter')),
    ('PLAYER_SHIP_VAMPWEED_3', ('battery', 'cloaking', 'drones', 'hacking', 'medbay')),
    ('PLAYER_SHIP_CARETAKER', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'mind', 'oxygen', 'sensors', 'teleporter')),
    ('PLAYER_SHIP_CARETAKER_2', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'mind', 'oxygen', 'teleporter')),
    ('PLAYER_SHIP_CARETAKER_3', ('battery', 'cloaking', 'drones', 'hacking', 'medbay', 'mind', 'sensors')),
    ('PLAYER_SHIP_CULTIVATOR', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'mind', 'teleporter')),
    ('PLAYER_SHIP_CULTIVATOR_2', ('battery', 'cloaking', 'hacking', 'medbay', 'mind', 'sensors')),
    ('PLAYER_SHIP_CULTIVATOR_3', ('cloaking', 'hacking', 'medbay', 'mind', 'teleporter')),
    ('PLAYER_SHIP_SHELL', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'mind', 'teleporter')),
    ('PLAYER_SHIP_SHELL_2', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'mind')),
    ('PLAYER_SHIP_SHELL_3', ('battery', 'cloaking', 'drones', 'hacking', 'medbay')),
    ('PLAYER_SHIP_SCIENTIST', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'mind', 'teleporter')),
    ('PLAYER_SHIP_SCIENTIST_2', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'mind', 'teleporter')),
    ('PLAYER_SHIP_SCIENTIST_3', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'medbay', 'teleporter')),
    ('PLAYER_SHIP_MECHANIC', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'mind', 'teleporter')),
    ('PLAYER_SHIP_MECHANIC_2', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'mind')),
    ('PLAYER_SHIP_MECHANIC_3', ('battery', 'drones', 'hacking', 'medbay', 'mind', 'shields', 'teleporter')),
    ('PLAYER_SHIP_LEECH', ('cloaking', 'clonebay', 'drones', 'hacking', 'mind')),
    ('PLAYER_SHIP_LEECH_2', ('cloaking', 'clonebay', 'drones', 'hacking', 'mind')),
    ('PLAYER_SHIP_LEECH_3', ('battery', 'drones', 'medbay', 'mind', 'sensors', 'shields')),
    ('PLAYER_SHIP_ALKRAM', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'mind')),
    ('PLAYER_SHIP_ALKRAM_2', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'medbay', 'mind')),
    ('PLAYER_SHIP_ALKRAM_3', ('battery', 'cloaking', 'drones', 'medbay', 'mind')),
    ('PLAYER_SHIP_TONY', ('cloaking', 'clonebay', 'drones', 'hacking', 'mind', 'teleporter')),
    ('PLAYER_SHIP_TONY_2', ('battery', 'cloaking', 'hacking', 'mind')),
    ('PLAYER_SHIP_TONY_3', ('cloaking', 'drones', 'hacking', 'medbay', 'mind')),
    ('PLAYER_SHIP_COALITION', ('battery', 'clonebay', 'drones', 'hacking', 'mind', 'sensors', 'shields')),
    ('PLAYER_SHIP_COALITION_2', ('battery', 'cloaking', 'drones', 'hacking', 'medbay', 'mind', 'shields')),
    ('PLAYER_SHIP_COALITION_3', ('battery', 'cloaking', 'doors', 'drones', 'hacking', 'medbay', 'sensors', 'teleporter')),
    ('PLAYER_SHIP_LANIUS', ('battery', 'cloaking', 'clonebay', 'drones', 'mind', 'oxygen', 'sensors')),
    ('PLAYER_SHIP_LANIUS_2', ('battery', 'cloaking', 'clonebay', 'hacking', 'mind', 'oxygen', 'teleporter')),
    ('PLAYER_SHIP_LANIUS_3', ('battery', 'drones', 'hacking', 'medbay', 'mind')),
    ('PLAYER_SHIP_DYNASTY', ('battery', 'clonebay', 'drones', 'hacking', 'mind', 'oxygen', 'shields', 'teleporter')),
    ('PLAYER_SHIP_DYNASTY_2', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'mind', 'oxygen', 'teleporter')),
    ('PLAYER_SHIP_DYNASTY_3', ('battery', 'cloaking', 'drones', 'hacking', 'medbay', 'mind', 'oxygen')),
    ('PLAYER_SHIP_GHOST', ('battery', 'cloaking', 'clonebay', 'hacking', 'mind', 'teleporter')),
    ('PLAYER_SHIP_GHOST_2', ('battery', 'cloaking', 'clonebay', 'drones', 'hacking', 'mind', 'sensors', 'teleporter')),
    ('PLAYER_SHIP_GHOST_3', ('cloaking', 'doors', 'drones', 'hacking', 'medbay', 'mind', 'teleporter')),
    ('PLAYER_SHIP_PLEASUREFLAG', ('battery', 'clonebay', 'hacking', 'medbay', 'mind', 'sensors', 'shields')),
    ('PLAYER_SHIP_STUPIDGHOST', ('battery', 'clonebay', 'drones', 'hacking', 'mind', 'oxygen')),
    ('PLAYER_SHIP_STUPIDGHOST_2', ('battery', 'cloaking', 'medbay', 'mind', 'oxygen', 'teleporter')),
    ('PLAYER_SHIP_STUPIDGHOST_3', ('battery', 'cloaking', 'doors', 'hacking', 'medbay', 'mind')),
)

MV_SHOP_ITEMS_RAW: tuple[tuple[int, str, str, str, int, int], ...] = (
    (0, 'weapon', 'LASER_BURST_3', 'Burst Laser MK II', 4, 70),
    (1, 'weapon', 'LASER_BURST_5', 'Burst Laser MK III', 4, 90),
    (2, 'weapon', 'LASER_HEAVY_1', 'Heavy Laser MK I', 2, 50),
    (3, 'weapon', 'LASER_HEAVY_2', 'Heavy Laser MK II', 4, 65),
    (4, 'weapon', 'MISSILES_3', "'Hermes' Heavy Missiles", 3, 60),
    (5, 'weapon', 'MISSILES_BURST', "'Pegasus' Burst Missiles", 3, 50),
    (6, 'weapon', 'BEAM_LONG', "'Pike' Beam", 2, 60),
    (7, 'weapon', 'BEAM_2', "'Halberd' Beam", 3, 70),
    (8, 'weapon', 'BEAM_3', "'Glaive' Beam", 5, 95),
    (9, 'weapon', 'BEAM_FIRE', "'Torch' Beam", 2, 50),
    (10, 'weapon', 'BEAM_BIO', "'Faucon' Rad-Beam", 5, 50),
    (11, 'weapon', 'LASER_HULL_1', 'Anti-Hull Laser MK I', 3, 55),
    (12, 'weapon', 'LASER_HULL_2', 'Anti-Hull Laser MK II', 3, 75),
    (13, 'weapon', 'BEAM_HULL', "'Lucerne' Beam", 3, 70),
    (14, 'weapon', 'ION_2', 'Ion Barrage MK I', 3, 40),
    (15, 'weapon', 'ION_4', 'Ion Barrage MK III', 5, 65),
    (16, 'weapon', 'BOMB_1', 'Bomb Launcher', 1, 45),
    (17, 'weapon', 'BOMB_FIRE', 'Fire Bomb', 3, 50),
    (18, 'weapon', 'BOMB_ION', 'Ion Bomb', 3, 55),
    (19, 'weapon', 'BOMB_HEAL', 'Medical Bomb', 4, 40),
    (0, 'drone', 'SHIP_REPAIR', 'Hull Repair', 4, 95),
    (1, 'drone', 'DEFENSE_1', 'Defender Drone Mk. I', 1, 55),
    (2, 'drone', 'DEFENSE_2', 'Defender Drone Mk. II', 3, 75),
    (3, 'drone', 'REPAIR', 'Maintenance Drone', 1, 40),
    (0, 'augment', 'ADV_SCANNERS', 'Long-Ranged Scanners', 1, 30),
    (1, 'augment', 'COMBAT_EXPLOSIVE', 'Magnetic Payload', 3, 40),
    (2, 'augment', 'EXTRA_PREP', 'Emergency Manual', 4, 30),
    (3, 'augment', 'COMBAT_REPAIR', 'Repair-Bot Dispersal', 5, 70),
    (4, 'augment', 'COMBAT_WEAPON_JAMMER', 'Targeting Jammer', 4, 40),
    (5, 'augment', 'COMBAT_SHIELDS_JAMMER', 'Shield Jammer', 4, 45),
    (6, 'augment', 'COMBAT_ENGINE_JAMMER', 'Engine Disabler', 3, 45),
    (7, 'augment', 'COMBAT_CLOAKING_JAMMER', 'Tracking Flares', 5, 75),
    (8, 'augment', 'COMBAT_WARP_JAMMER', 'Disruption Field', 5, 50),
    (9, 'augment', 'COMBAT_REACTOR_JAMMER', 'EMP Field', 5, 90),
    (10, 'augment', 'COMBAT_OXYGEN_JAMMER', 'Asphyxiator', 5, 45),
    (11, 'augment', 'RECYCLER', 'Recycler Module', 3, 50),
    (12, 'augment', 'RECYCLER_REVERSE', 'Deconstructor', 3, 40),
    (13, 'augment', 'STORE_BEACON', 'Merchant Beacon', 5, 45),
    (14, 'augment', 'DISTRACTION_BUOY', 'Decoy Buoys', 3, 50),
    (15, 'augment', 'PRE_SCANNER', 'Slip-Scanner', 4, 50),
    (16, 'augment', 'FUEL_CONSERVER', 'Fuel Conserver', 2, 20),
    (17, 'augment', 'PDS_DISABLE', 'Signal Diluter', 4, 45),
    (18, 'augment', 'ANTI_VIRUS', 'Anti-Virus Module', 4, 30),
    (19, 'augment', 'CREW_FIREARMS', 'Improved Armories', 3, 45),
    (20, 'augment', 'SPEED_SUITS', 'Exovests', 3, 40),
    (21, 'augment', 'CREW_OXYGEN', 'Advanced Ventilation', 2, 40),
    (20, 'weapon', 'LASER_BURST_2', 'Burst Laser MK I', 3, 50),
    (21, 'weapon', 'LASER_HEAVY_3', 'Heavy Laser MK III', 5, 80),
    (22, 'weapon', 'LASER_HEAVY_CHAINGUN', 'Chain Heavy Laser', 4, 55),
    (23, 'weapon', 'LASER_HEAVY_PIERCE', 'Piercing Heavy Laser', 4, 65),
    (24, 'weapon', 'LASER_HULL_3', 'Anti-Hull Laser MK III', 5, 85),
    (25, 'weapon', 'LASER_HULL_CHAINGUN', 'Chain Anti-Hull Laser', 4, 60),
    (26, 'weapon', 'LASER_LIGHT', 'Light Laser MK I', 3, 35),
    (27, 'weapon', 'LASER_LIGHT_2', 'Light Laser MK II', 4, 55),
    (28, 'weapon', 'LASER_PIERCE', 'Pierce Laser MK I', 3, 60),
    (29, 'weapon', 'LASER_PIERCE_2', 'Pierce Laser MK II', 5, 95),
    (30, 'weapon', 'LASER_CHAINGUN', 'Chain Burst Laser', 3, 50),
    (31, 'weapon', 'LASER_CHAINGUN_2', 'Chain Vulcan', 5, 75),
    (32, 'weapon', 'LASER_CHARGEGUN', 'Charge Laser MK I', 3, 55),
    (33, 'weapon', 'LASER_CHARGEGUN_2', 'Charge Laser MK II', 3, 75),
    (34, 'weapon', 'LASER_CHARGEGUN_3', 'Charge Laser MK III', 5, 100),
    (35, 'weapon', 'LASER_CHARGE_CHAIN', 'Laser Chainger', 3, 45),
    (36, 'weapon', 'LASER_CHAINGUN_DAMAGE', 'Adaptive Laser', 4, 60),
    (37, 'weapon', 'LASER_FIRE', 'Fire-Starter', 3, 60),
    (38, 'weapon', 'LASER_STUN', 'Neural Laser', 3, 55),
    (39, 'weapon', 'LASER_FROST_1', 'Frost Laser MK I', 3, 70),
    (40, 'weapon', 'LASER_FROST_2', 'Frost Laser MK II', 4, 80),
    (41, 'weapon', 'LASER_BIO', 'Irradiation Laser', 5, 50),
    (42, 'weapon', 'LASER_PARTICLE', 'Particle Accelerator MK I', 3, 60),
    (43, 'weapon', 'LASER_PARTICLE_2', 'Particle Accelerator MK II', 4, 80),
    (44, 'weapon', 'BEAM_PARTICLE', 'Particle Beam', 3, 65),
    (45, 'weapon', 'MISSILES_PARTICLE', 'Particle Missile', 5, 75),
    (46, 'weapon', 'ION_3', 'Ion Barrage MK II', 4, 55),
    (47, 'weapon', 'ION_HEAVY', 'Heavy Ion', 3, 55),
    (48, 'weapon', 'ION_TRI', 'Tri-Ion', 4, 55),
    (49, 'weapon', 'ION_INSTANT', 'Pre-emptive Ion Blast', 5, 65),
    (50, 'weapon', 'ION_CHAINGUN', 'Adaptive Ion', 4, 55),
    (51, 'weapon', 'ION_CHARGEGUN', 'Ion Charger', 3, 50),
    (52, 'weapon', 'ION_CHARGEGUN_2', 'Ion Charger II', 3, 65),
    (53, 'weapon', 'ION_STUN', 'Stunner MK I', 3, 40),
    (54, 'weapon', 'ION_STUN_2', 'Stunner MK II', 4, 50),
    (55, 'weapon', 'ION_STUN_HEAVY', 'Heavy Stunner', 3, 65),
    (56, 'weapon', 'ION_STUN_CHARGEGUN', 'Charge Stunner', 4, 50),
    (57, 'weapon', 'ION_PIERCE_1', 'Phaser MK I', 3, 50),
    (58, 'weapon', 'ION_PIERCE_2', 'Phaser MK II', 4, 70),
    (59, 'weapon', 'ION_FIRE', 'Fire Ion Blast', 5, 55),
    (60, 'weapon', 'ION_BIO', 'Radion Barrage', 5, 65),
    (61, 'weapon', 'MISSILES_2', "'Artemis' Heavy Missiles", 2, 45),
    (62, 'weapon', 'MISSILES_4', "'Ares' Heavy Missiles", 3, 90),
    (63, 'weapon', 'MISSILES_BURST_2', "'Hydra' Burst Missiles", 4, 65),
    (64, 'weapon', 'MISSILES_CLOAK', "'Nyx' Missiles", 3, 80),
    (65, 'weapon', 'MISSILES_FIRE', "'Hades' Missiles", 4, 70),
    (66, 'weapon', 'MISSILES_FREE', "'Momus' Missiles", 5, 55),
    (67, 'weapon', 'MISSILES_BIO', "'Asclepius' Missiles", 4, 60),
    (68, 'weapon', 'MISSILES_STUN', "'Eris' Missiles", 4, 60),
    (69, 'weapon', 'BEAM_1', "'Spetum' Beam", 3, 50),
    (70, 'weapon', 'BEAM_4', "'Voulge' Beam", 5, 110),
    (71, 'weapon', 'BEAM_LONG_2', "'Sarissa' Beam", 5, 90),
    (72, 'weapon', 'BEAM_SCYTHE', "'Scythe' Beam", 4, 55),
    (73, 'weapon', 'BEAM_CHAIN', "'Corseque' Beam", 4, 75),
    (74, 'weapon', 'BEAM_PIERCE', "'Guisarme' Beam", 5, 65),
    (75, 'weapon', 'BEAM_FIRE_PIERCE', "'Flamberge' Beam", 5, 65),
    (76, 'weapon', 'BEAM_FIRE_INSTANT', "Pre-emptive 'Torch'", 5, 100),
    (77, 'weapon', 'BEAM_BREACH', "'Ranseur' Beam", 3, 50),
    (78, 'weapon', 'BEAM_HULL_2', "'Goedendag' Beam", 5, 90),
    (79, 'weapon', 'BEAM_MINING', 'Zulfiqar Mining Beam', 5, 70),
    (80, 'weapon', 'BEAM_ADAPT', "'Suyari' Beam", 4, 80),
    (81, 'weapon', 'BEAM_ADAPT_2', "'Kamayari' Beam", 5, 110),
    (82, 'weapon', 'BEAM_BIO_CHAIN', "'Corbin' Rad-Beam", 5, 50),
    (83, 'weapon', 'BEAM_STUN', "'Partisan' Beam", 5, 50),
    (84, 'weapon', 'BEAM_GUILLOTINE', "'Fauchard' Beam", 5, 70),
    (85, 'weapon', 'FOCUS_1', "'Dirk' Pinpoint", 2, 45),
    (86, 'weapon', 'FOCUS_2', "'Misericorde' Pinpoint", 4, 80),
    (87, 'weapon', 'FOCUS_3', "'Stiletto' Pinpoint", 5, 95),
    (88, 'weapon', 'FOCUS_CHAIN', "'Cinquedea' Pinpoint", 5, 90),
    (89, 'weapon', 'FOCUS_BIO', "'Anelace' Rad-Pinpoint", 5, 45),
    (90, 'weapon', 'BOMB_BREACH_1', 'Breach Bomb', 3, 50),
    (91, 'weapon', 'BOMB_FREE', 'Recycler Bomb', 4, 52),
    (92, 'weapon', 'BOMB_STUN', 'Stun Bomb', 4, 60),
    (93, 'weapon', 'BOMB_BIO', 'Irradiation Bomb', 3, 50),
    (94, 'weapon', 'BOMB_HEAL_SYSTEM', 'Repair Burst', 4, 40),
    (95, 'weapon', 'BOMB_BUFF', 'Stimulant Bomb', 5, 60),
    (96, 'weapon', 'ENERGY_1', 'Energy Cannon I', 2, 40),
    (97, 'weapon', 'ENERGY_2', 'Energy Cannon II', 3, 60),
    (98, 'weapon', 'ENERGY_3', 'Energy Cannon III', 5, 70),
    (99, 'weapon', 'ENERGY_HULL', 'Heavy Energy', 4, 50),
    (100, 'weapon', 'ENERGY_STUN', 'Energy Stunner', 4, 55),
    (101, 'weapon', 'ENERGY_CHAINGUN', 'Chain Energy', 3, 70),
    (102, 'weapon', 'ENERGY_CHARGEGUN', 'Energy Charger', 3, 65),
    (103, 'weapon', 'SHOTGUN_1', 'Flak Gun MK I', 3, 45),
    (104, 'weapon', 'SHOTGUN_2', 'Flak Gun MK II', 1, 65),
    (105, 'weapon', 'SHOTGUN_3', 'Flak Gun MK III', 4, 90),
    (106, 'weapon', 'SHOTGUN_4', 'Flak Gun MK IV', 5, 110),
    (107, 'weapon', 'SHOTGUN_CHARGE', 'Flak Charger', 4, 65),
    (108, 'weapon', 'SHOTGUN_CHAIN', 'Chain Flak Gun', 4, 80),
    (109, 'weapon', 'SHOTGUN_INSTANT', 'Pre-emptive Flak', 5, 70),
    (110, 'weapon', 'SHOTGUN_FIRE', 'Ignited Flak Gun', 5, 80),
    (111, 'weapon', 'SHOTGUN_ION', 'Electrified Flak Gun', 5, 80),
    (112, 'weapon', 'SHOTGUN_TOXIC', 'Irradiated Flak Gun', 5, 80),
    (113, 'weapon', 'LASER_CONSERVATIVE', 'Conservative Laser', 3, 60),
    (114, 'weapon', 'BEAM_CONSERVATIVE', "'Spontoon' Beam", 4, 50),
    (115, 'weapon', 'ION_CONSERVATIVE', 'Conservative Ion', 4, 35),
    (116, 'weapon', 'MISSILES_CONSERVATIVE', "'Tyche' Missiles", 3, 45),
    (117, 'weapon', 'BOMB_CONSERVATIVE', 'Conservative Bomb', 3, 45),
    (118, 'weapon', 'ENERGY_CONSERVATIVE', 'Conservative Energy', 5, 45),
    (119, 'weapon', 'BEAM_BIO_CONSERVATIVE', "'Pelta' Rad-Beam", 5, 50),
    (4, 'drone', 'DEFENSE_3', 'Defender Drone Mk. III', 5, 135),
    (5, 'drone', 'GUARDIAN_1_MISSILE', 'Guardian Drone Mk. I [M]', 2, 57),
    (6, 'drone', 'GUARDIAN_2_MISSILE', 'Guardian Drone Mk. II [M]', 3, 65),
    (7, 'drone', 'COMBAT_1_LASER', 'Combat Drone Mk. I [Laser]', 1, 60),
    (8, 'drone', 'COMBAT_2_LASER', 'Combat Drone Mk. II [Laser]', 4, 85),
    (9, 'drone', 'COMBAT_CONSERVATIVE_LASER', 'Conservative Drone [Laser]', 3, 55),
    (10, 'drone', 'ASSAULT_PARTICLE', 'Assault Drone [Particle]', 3, 65),
    (11, 'drone', 'HELLRAISER_FIRE', 'Hellraiser [Fire]', 4, 60),
    (12, 'drone', 'PEST_RAD', 'Pestilence Drone [RAD]', 4, 45),
    (13, 'drone', 'ION_1_AMP2', 'Amp Ion', 3, 50),
    (14, 'drone', 'ENERGY_1_AMP2', 'Amp Energy', 4, 60),
    (15, 'drone', 'FOCUS_1_AMP2', 'Amp Pinpoint', 3, 55),
    (16, 'drone', 'FLAK_1_AMP2', 'Amp Flak', 3, 50),
    (17, 'drone', 'RECON_BOARDER', 'Recon Drone [Boarding]', 3, 25),
    (18, 'drone', 'BATTLETOG_DEFEND', 'Battle Drone [Anti-Pers]', 2, 50),
    (19, 'drone', 'BATTLETOG2_DEFEND', 'Battle Drone Mk. II [Anti-Pers]', 3, 70),
    (20, 'drone', 'DOCTOR_DEFENSE', 'Dr. Drone [Defend]', 3, 50),
    (21, 'drone', 'MANNING', 'Manager Drone', 2, 45),
    (22, 'drone', 'AMPHI_DEFENSE', 'Amphi-Drone [Defense]', 3, 60),
    (23, 'drone', 'DRONE_SHIELD', 'Energized Overcharger', 4, 50),
    (24, 'drone', 'BOARDER_ION', 'Ion Intruder Drone', 4, 65),
)

MV_ACHIEVEMENTS_RAW: tuple[tuple[int, str, str], ...] = (
    (0, 'ACH_ACC_DATABASE', 'Well Informed'),
    (1, 'ACH_ACC_25DEATHS', 'Been There, Done That'),
    (2, 'ACH_ACC_SIGNAL', 'Transmission Received'),
    (3, 'ACH_ACC_DIVE', 'Deep Dive'),
    (4, 'ACH_ACC_TOURIST', 'Tourist'),
    (5, 'ACH_ACC_LAB', 'Advancing Evolution'),
    (6, 'ACH_ACC_UPG', 'Overclocked'),
    (7, 'ACH_ACC_SOCIALIZE', 'Sociable'),
    (8, 'ACH_ACC_OBSIDIAN', 'Unbreakable'),
    (9, 'ACH_ACC_ITB', 'Once More Unto the Breach'),
    (10, 'ACH_ACC_DETERGENT', 'Detergent Mode'),
    (11, 'ACH_EVENT_DARWIN', 'A Dubious Investment'),
    (12, 'ACH_EVENT_HORRIBLEDEMON', 'The Horrible Demon'),
    (13, 'ACH_EVENT_COUNT', 'Chip Chip Cheerio'),
    (14, 'ACH_EVENT_QUICKDRAW', 'Quick Draw'),
    (15, 'ACH_EVENT_BOLINE', 'Reading Comprehension'),
    (16, 'ACH_EVENT_MYSTERY', "It's Elementary"),
    (17, 'ACH_EVENT_PUPPET', 'Untangling the Strings'),
    (18, 'ACH_EVENT_EXPLOSION', 'No Survivors - Except Me'),
    (19, 'ACH_EVENT_GATLING', 'B.F.G.'),
    (20, 'ACH_EVENT_KASPAROV', 'The Something-Ov'),
    (21, 'ACH_EVENT_KYLE', 'Ass Kicked'),
    (22, 'ACH_EVENT_STORYTELLER', 'A Story of a Boy'),
    (23, 'ACH_EVENT_BUTTBUDDIES', 'Butt Buddies'),
    (24, 'ACH_ACC_DOORSONG', 'No Entry'),
    (25, 'ACH_EVENT_HIGHWAYMAN', 'The Best Defense Is a Good Offense'),
)
