"""Presets shown on the options page. Built from presets/*.yaml, test_presets checks they still match."""

PRESET_FILES = {
    "Among other games, new to FTL": "A1_multi_game_beginner.yaml",
    "Among other games, FTL veteran": "A2_multi_game_veteran.yaml",
    "Two evenings, new to FTL": "C1_two_evenings_beginner.yaml",
    "Two evenings, FTL veteran": "C2_two_evenings_veteran.yaml",
    "FTL alone, long, new to FTL": "B1_solo_beginner.yaml",
    "FTL alone, long, FTL veteran": "B2_solo_veteran.yaml",
}

OPTIONS_PRESETS = {
    "Recommended": {"death_link": True},
    "Among other games, new to FTL": {
        "goal": "victory_count",
        "victories_required": 1,
        "start_ship": "kestrel_cruiser",
        "ship_layouts": "type_a_only",
        "layout_unlocks": "vanilla",
        "sectorsanity": "full",
        "sectorsanity_first_sector": 1,
        "sectorsanity_last_sector": 4,
        "ship_achievements": False,
        "general_achievements": "basic",
        "cross_run_achievements": False,
        "shop_checks": 25,
        "minimum_filler": 5,
        "crew_members": False,
        "system_blueprints": True,
        "progressive_systems": True,
        "head_starts": True,
        "trap_chance": 0,
        "shop_weapons": 8,
        "shop_drones": 3,
        "shop_augments": 4,
        "shop_unlock_mode": "rarity_boost",
        "shop_item_delivery": True,
        "sector_logic": "relaxed",
        "shields_blueprint_logic": "start_with",
        "sensors_blueprint_logic": "start_with",
        "medbay_blueprint_logic": "start_with",
        "engines_blueprint_logic": "start_with",
        "weapons_blueprint_logic": "start_with",
        "death_link": False,
        "energy_link": True,
        "trap_link": False,
        "mod_language": "game",
        "victory_difficulty": "any",
        "archives": 0,
        "archives_required": 0,
    },
    "Among other games, FTL veteran": {
        "goal": "victory_count",
        "victories_required": 1,
        "start_ship": "stealth_cruiser",
        "ship_layouts": "type_a_only",
        "layout_unlocks": "vanilla",
        "sectorsanity": "full",
        "sectorsanity_first_sector": 2,
        "sectorsanity_last_sector": 5,
        "ship_achievements": True,
        "general_achievements": "basic",
        "cross_run_achievements": False,
        "shop_checks": 25,
        "minimum_filler": 5,
        "crew_members": False,
        "system_blueprints": True,
        "progressive_systems": True,
        "head_starts": True,
        "trap_chance": 20,
        "shop_weapons": 15,
        "shop_drones": 6,
        "shop_augments": 9,
        "shop_unlock_mode": "locked",
        "shop_item_delivery": True,
        "sector_logic": "standard",
        "shields_blueprint_logic": "required",
        "sensors_blueprint_logic": "upgrade_only",
        "medbay_blueprint_logic": "upgrade_only",
        "engines_blueprint_logic": "early",
        "weapons_blueprint_logic": "early",
        "death_link": True,
        "death_link_trigger": "ship_destroyed",
        "death_link_effect": "varied",
        "energy_link": True,
        "trap_link": True,
        "mod_language": "game",
        "victory_difficulty": "any",
        "archives": 0,
        "archives_required": 0,
    },
    "Two evenings, new to FTL": {
        "goal": "victory_count",
        "victories_required": 2,
        "start_ship": "kestrel_cruiser",
        "ship_layouts": "type_a_only",
        "layout_unlocks": "vanilla",
        "sectorsanity": "full",
        "sectorsanity_first_sector": 2,
        "sectorsanity_last_sector": 6,
        "ship_achievements": False,
        "general_achievements": "basic",
        "cross_run_achievements": False,
        "shop_checks": 30,
        "minimum_filler": 5,
        "crew_members": False,
        "system_blueprints": True,
        "progressive_systems": True,
        "head_starts": True,
        "trap_chance": 0,
        "shop_weapons": 10,
        "shop_drones": 4,
        "shop_augments": 6,
        "shop_unlock_mode": "rarity_boost",
        "shop_item_delivery": True,
        "sector_logic": "relaxed",
        "shields_blueprint_logic": "start_with",
        "sensors_blueprint_logic": "upgrade_only",
        "medbay_blueprint_logic": "upgrade_only",
        "engines_blueprint_logic": "start_with",
        "weapons_blueprint_logic": "start_with",
        "death_link": False,
        "energy_link": True,
        "trap_link": False,
        "mod_language": "game",
        "victory_difficulty": "any",
        "archives": 0,
        "archives_required": 0,
    },
    "Two evenings, FTL veteran": {
        "goal": "victory_selection",
        "victory_layouts": ["Stealth Cruiser B", "Engi Cruiser B", "Rock Cruiser B"],
        "start_ship": "lanius_cruiser",
        "ship_layouts": "up_to_type_b",
        "layout_unlocks": "items",
        "sectorsanity": "full",
        "sectorsanity_first_sector": 5,
        "sectorsanity_last_sector": 7,
        "ship_achievements": True,
        "general_achievements": "most",
        "cross_run_achievements": False,
        "shop_checks": 30,
        "minimum_filler": 5,
        "crew_members": False,
        "system_blueprints": True,
        "progressive_systems": True,
        "head_starts": True,
        "trap_chance": 15,
        "shop_weapons": 20,
        "shop_drones": 8,
        "shop_augments": 12,
        "shop_unlock_mode": "locked",
        "shop_item_delivery": False,
        "sector_logic": "standard",
        "shields_blueprint_logic": "upgrade_only",
        "sensors_blueprint_logic": "upgrade_only",
        "medbay_blueprint_logic": "required",
        "engines_blueprint_logic": "early",
        "weapons_blueprint_logic": "early",
        "death_link": True,
        "death_link_trigger": "crew_death",
        "death_link_effect": "varied",
        "energy_link": True,
        "trap_link": True,
        "mod_language": "game",
        "victory_difficulty": "any",
        "archives": 0,
        "archives_required": 0,
    },
    "FTL alone, long, new to FTL": {
        "goal": "victory_count",
        "victories_required": 3,
        "start_ship": "kestrel_cruiser",
        "ship_layouts": "all_layouts",
        "layout_unlocks": "items",
        "sectorsanity": "full",
        "sectorsanity_first_sector": 3,
        "sectorsanity_last_sector": 8,
        "ship_achievements": True,
        "general_achievements": "most",
        "cross_run_achievements": False,
        "shop_checks": 40,
        "system_blueprints": True,
        "progressive_systems": True,
        "head_starts": True,
        "trap_chance": 0,
        "shop_weapons": 30,
        "shop_drones": 11,
        "shop_augments": 19,
        "shop_unlock_mode": "rarity_boost",
        "shop_item_delivery": True,
        "sector_logic": "relaxed",
        "shields_blueprint_logic": "upgrade_only",
        "sensors_blueprint_logic": "upgrade_only",
        "medbay_blueprint_logic": "upgrade_only",
        "engines_blueprint_logic": "early",
        "weapons_blueprint_logic": "early",
        "death_link": False,
        "energy_link": False,
        "trap_link": False,
        "mod_language": "game",
        "victory_difficulty": "any",
        "archives": 0,
        "archives_required": 0,
    },
    "FTL alone, long, FTL veteran": {
        "goal": "victory_selection",
        "victory_layouts": ["Stealth Cruiser B", "Engi Cruiser B", "Rock Cruiser B", "Zoltan Cruiser B"],
        "start_ship": "slug_cruiser",
        "ship_layouts": "all_layouts",
        "layout_unlocks": "items",
        "sectorsanity": "full",
        "sectorsanity_first_sector": 3,
        "sectorsanity_last_sector": 8,
        "ship_achievements": True,
        "general_achievements": "all",
        "cross_run_achievements": True,
        "shop_checks": 50,
        "system_blueprints": True,
        "progressive_systems": True,
        "head_starts": True,
        "trap_chance": 30,
        "shop_weapons": 30,
        "shop_drones": 11,
        "shop_augments": 19,
        "shop_unlock_mode": "locked",
        "shop_item_delivery": False,
        "sector_logic": "strict",
        "shields_blueprint_logic": "upgrade_only",
        "sensors_blueprint_logic": "required",
        "medbay_blueprint_logic": "upgrade_only",
        "engines_blueprint_logic": "anywhere",
        "weapons_blueprint_logic": "anywhere",
        "death_link": False,
        "energy_link": False,
        "trap_link": False,
        "mod_language": "game",
        "victory_difficulty": "any",
        "archives": 0,
        "archives_required": 0,
    },
}
