#!/usr/bin/env python3

from __future__ import annotations

import argparse
import asyncio
import json
import os
import shutil
import socket as socket_module
import subprocess
import sys
import tempfile
import time
import types
from pathlib import Path

AP = Path(os.environ.get("AP_ROOT", "~/.local/opt/Archipelago")).expanduser()
GAME = "FTL: Faster Than Light"
PORT = 38299

_SEED_ARGUMENT = next(
    (Path(argument).resolve() for argument in sys.argv[1:]
     if not argument.startswith("-") and Path(argument).is_file()),
    None,
)

os.chdir(AP)
_stub = types.ModuleType("bsdiff4.core")
_stub.diff = _stub.patch = lambda *a, **k: b""
sys.modules["bsdiff4.core"] = _stub
sys.path.append(str(AP / "lib" / "library.zip"))
sys.path.append(str(AP / "lib"))

import websockets  # noqa: E402

REQUIRED_SLOT_DATA = ("contract", "kinds", "kinds_required", "items", "loc", "start_ship", "goal")


class Failure(Exception):
    pass


async def send(socket, *messages) -> None:
    await socket.send(json.dumps(list(messages)))


def connect_payload(slot: str) -> dict:
    return {
        "cmd": "Connect", "game": GAME, "name": slot, "password": None,
        "uuid": "ftl-roundtrip", "version": {"major": 0, "minor": 6, "build": 7,
                                             "class": "Version"},
        "items_handling": 0b111, "tags": [], "slot_data": True,
    }


async def expect(socket, command: str, timeout: float = 20.0) -> dict:
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        raw = await asyncio.wait_for(socket.recv(), timeout=deadline - time.monotonic())
        for message in json.loads(raw):
            if message["cmd"] == command:
                return message
            if message["cmd"] == "ConnectionRefused":
                raise Failure(f"connection refused: {message.get('errors')}")
    raise Failure(f"no \"{command}\" within the time given")


async def roundtrip(slot: str, report: list[str]) -> None:
    uri = f"ws://localhost:{PORT}"
    async with websockets.connect(uri, max_size=None) as socket:
        room = await expect(socket, "RoomInfo")
        if GAME not in room.get("games", []):
            raise Failure(f"\"{GAME}\" missing from the announced games: {room.get('games')}")
        report.append(f"1. RoomInfo: {len(room.get('games', []))} games, ours included")

        await send(socket, connect_payload(slot))
        connected = await expect(socket, "Connected")
        report.append(
            f"2. Connected: slot {connected['slot']}, "
            f"{len(connected['missing_locations'])} locations to do"
        )

        slot_data = connected.get("slot_data") or {}
        SEED_REMINDER = (", this seed may have been generated by an apworld older than the "
                         "expected field. Regenerate with apworld/multiworld/make.sh before "
                         "suspecting the code.")
        missing = [field for field in REQUIRED_SLOT_DATA if field not in slot_data]
        if "language" not in slot_data:
            missing.append("language")
        if missing:
            raise Failure(f"incomplete slot_data, missing: {', '.join(missing)}{SEED_REMINDER}")
        report.append(
            f"3. slot_data: contract v{slot_data['contract']}, "
            f"{len(slot_data['items'])} items described, {len(slot_data['loc'])} check keys, "
            f"language = {slot_data['language']!r}"
        )

        sample = sorted(connected["missing_locations"])[:120]
        if not sample:
            raise Failure("no location to do: seed already finished?")
        await send(socket, {"cmd": "LocationScouts", "locations": sample, "create_as_hint": 0})
        scouted = await expect(socket, "LocationInfo")
        report.append(
            f"4. LocationScouts: {len(scouted['locations'])} locations read without validating them"
        )

        ours = [
            item["location"] for item in scouted["locations"]
            if item["player"] == connected["slot"]
        ]
        if not ours:
            raise Failure(
                f"none of the first {len(sample)} locations holds one of our items: "
                "cannot check reception"
            )
        targets = ours[:5]
        await send(socket, {"cmd": "LocationChecks", "locations": targets})
        received = await expect(socket, "ReceivedItems")
        if len(received["items"]) < len(targets):
            raise Failure(
                f"{len(targets)} locations validated, only "
                f"{len(received['items'])} items received"
            )
        report.append(
            f"5. LocationChecks: {len(targets)} of our locations validated, "
            f"{len(received['items'])} items received back"
        )
        checked_count = len(targets)

    await asyncio.sleep(0.5)
    async with websockets.connect(uri, max_size=None) as socket:
        await expect(socket, "RoomInfo")
        await send(socket, connect_payload(slot))
        again = await expect(socket, "Connected")
        if len(again["checked_locations"]) < checked_count:
            raise Failure(
                f"after reconnecting, the server only remembers "
                f"{len(again['checked_locations'])} checks out of {checked_count}"
            )
        report.append(
            f"6. Resume: the server remembers the {len(again['checked_locations'])} checks"
        )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("seed", type=Path)
    parser.add_argument("--slot", default="Player")
    arguments = parser.parse_args()

    seed = _SEED_ARGUMENT or arguments.seed.resolve()
    if not seed.is_file():
        sys.exit(f"seed not found: {seed}")

    workdir = Path(tempfile.mkdtemp(prefix="ftl-roundtrip-"))
    working_seed = workdir / seed.name
    shutil.copy2(seed, working_seed)

    server = subprocess.Popen(
        [str(AP / "ArchipelagoServer"), str(working_seed), "--port", str(PORT)],
        cwd=AP, stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
        stdin=subprocess.DEVNULL, text=True,
    )
    report: list[str] = []
    try:
        for _ in range(60):
            time.sleep(0.5)
            if server.poll() is not None:
                sys.exit("the server stopped while starting up")
            with socket_module.socket() as probe:
                probe.settimeout(1.0)
                if probe.connect_ex(("127.0.0.1", PORT)) == 0:
                    break
        else:
            sys.exit("the server still is not listening")

        asyncio.run(roundtrip(arguments.slot, report))
    except Failure as error:
        for line in report:
            print(f"  {line}")
        print(f"  FAIL: {error}", file=sys.stderr)
        return 1
    finally:
        server.terminate()
        try:
            server.wait(timeout=10)
        except subprocess.TimeoutExpired:
            server.kill()
        shutil.rmtree(workdir, ignore_errors=True)

    for line in report:
        print(f"  {line}")
    print("  full round trip: the apworld does talk to the server")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
